/* Silk Road battle UI: original art, click deployment, no dependencies. */
(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('world'),ctx=C.getContext('2d'),E=SilkBattle,KEY=()=>window.SilkStudent.storageKey();
let state=E.initial(),battle,paused=false,selected=null,last=0,W=1200,H=500,selectedUnit=null,modalAction=null,altAction=null,lastStatus='',imagesReady=0,fourthClock=null;
const keys=Object.keys(E.TYPES),images={};
for(const key of [...keys,'archer','crow','worm']){const im=new Image();images[key]=im;im.onload=()=>{imagesReady++;};im.onerror=()=>say('角色圖片尚未讀取成功，請確認 assets 資料夾完整後重新整理。');im.src=`assets/${key}/${['crow','worm'].includes(key)?'sheet.svg':'sheet-transparent.png'}`;}
const stories=[
 '漢武帝派張騫聯絡大月氏，希望結盟對抗匈奴。你帶著絲綢從長安出發，護送商隊穿過玉門關。這不是單純的買賣，也是一次外交冒險。',
 '十餘年後，張騫趁匈奴防備鬆懈逃出，繼續前往大月氏。本關從匈奴據點出發，依本遊戲城市規則，只能購買葡萄・琵琶商品馬。',
 '大月氏不願結盟，張騫仍帶回珍貴的西域見聞。護送葡萄與琵琶返回長安，讓物產與音樂隨商隊交流。',
 '後世商隊接棒，往返長安與大秦。從長安帶絲綢西行，再從大秦帶葡萄與琵琶東歸；扣除購買動物的費用，累積淨獲利 10,000 元。小心驚盗鴉約每 10 秒從空中抓馬（無馬時攻擊駱駝），以及沙蟲約每 15 秒在終點附近吞馬；馬與貨物會一同損失。'
];
function say(t){if(lastStatus!==t){lastStatus=t;$('message').textContent=t;}}
function save(){try{localStorage.setItem(KEY(),JSON.stringify(state));}catch{say('本瀏覽器無法儲存進度；本次仍可繼續遊玩。');}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY()));if(s&&Number.isInteger(s.chapter)&&s.chapter>=0&&s.chapter<4&&['out','back'].includes(s.leg)&&Number.isFinite(s.money)&&s.money>=0&&(s.baseline===null||Number.isFinite(s.baseline))&&Number.isInteger(s.round)&&s.round>0)state=s;if(state.chapter===3&&!state.ended&&state.fourthSchedule!==2)state={...state,money:state.baseline??state.money,leg:'out',round:1,fourthElapsed:0,fourthTotals:{passed:0,goods:0,spent:0,revenue:0},fourthSchedule:2,enemyClock:null};}catch{}}
function modal(tag,title,body,label,action,altLabel='',alt=null){$('dialogHome').hidden=true;$('dialogTag').textContent=tag;$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialogOK').textContent=label;$('dialogAlt').textContent=altLabel;$('dialogAlt').hidden=!altLabel;modalAction=action;altAction=alt;if(!$('dialog').open)$('dialog').showModal();}
$('dialogOK').onclick=()=>{$('dialog').close();const fn=modalAction;modalAction=null;if(fn)fn();};$('dialogAlt').onclick=()=>{$('dialog').close();const fn=altAction;altAction=null;if(fn)fn();};$('dialog').addEventListener('cancel',e=>e.preventDefault());
function rules(){return `<ul><li><b>點擊下方動物卡</b>即可購買並從出發點移動。長安出發及第二關由左往右；返回長安由右往左。</li><li>駱駝各帶一種固定道具，不能載貨。先派浮沙踏板、防風罩或引仇盾駱駝；到對應危險前會自動停下。</li><li>駐守者持續扣血：流沙 2／秒、龍捲風 5／秒。沒有道具且沒有守護，碰到陷阱立即死亡。弓箭手原地每秒射一箭，傷害 10，優先攻擊射程內引仇盾。</li><li>商品馬有 60 生命，載 5 單位貨物，出發後持續前進；絲綢馬 100 元／售 300 元，葡萄・琵琶馬 140 元／售 540 元。</li><li>第一關經費 5,000 元。第一關 <b>40 秒</b>，第二、三關各 <b>60 秒</b>，只結算抵達終點的商品馬；未抵達不算收入。經費與收入延續到下一關。</li><li>第四關為現實時間 180 秒：前 90 秒長安 → 大秦，後 90 秒自動改為大秦 → 長安。切換時已抵達收入自動入帳，未抵達商品不計收入，原商隊與攻擊效果清場，需重新購買動物。第 180 秒統一總結算；說明視窗及切換分頁不暫停計時。</li><li>第四關限定怪物：<b>驚盗鴉</b>約每 8–12 秒從空中現身，優先抓走一匹馬與全部貨物；沒有馬時啄擊駱駝（30 傷害），沒有動物就飛離。<b>沙蟲</b>約每 13–17 秒在終點附近破沙而出，停留約 5 秒，只吞噬附近一匹馬與貨物。換城不重置怪物出現倒數。</li></ul>`;}
function startRound(){fourthClock=null;if(!state.runId)state.runId=crypto.randomUUID();battle=new E.Battle(state);paused=false;selected=null;selectedUnit=null;lastStatus='';$('unitInfo').hidden=true;buildCards();hud();save();if(state.ended){window.SilkStudent.complete(state.finalScore??state.money,state.runId);showFinal();return;}const r=battle.route;modal(r.tag,r.title,`<p>${stories[state.chapter]}</p>${state.chapter===0?rules():`<p>本次：<b>${r.origin} → ${r.destination}</b>。可用經費 <b>${state.money.toLocaleString()} 元</b>。${state.chapter<3?`限時 ${battle.timeLimit} 秒，時間到統一結算。`:`前 90 秒西行，後 90 秒自動東歸，不用按結算。現實時間 180 秒到統一判定；切換時未抵達商品不計收入。`}</p><p>先派駱駝建立安全通道，再讓商品馬出發。</p>`}<div class="note">${state.chapter===0?'張騫被俘是真實經歷；玉門關地標、勇氣交易及 40 秒護送是遊戲改編。':state.chapter===1?'此關葡萄／琵琶交易是遊戲規則，不表示張騫逃出時曾攜帶這些商品。':'商品、裝備與直接往返大秦均為教學遊戲的簡化；不代表所有商品都由張騫本人帶回。'}</div>`,'開始商隊出擊 →',()=>{battle.begin();if(state.chapter===3)fourthClock=performance.now()-battle.time*1000;say('點擊下方卡片即可從出發點出發。先派守護駱駝，再派商品馬。');hud();});}
function buildCards(){$('cards').innerHTML=keys.map((key,i)=>{const t=E.TYPES[key];return `<button type="button" class="unit-card" data-unit="${key}" ${!E.available(state,key)?'hidden':''} aria-label="購買${t.name}，${t.cost}元；點擊即可從出發點出發"><div class="card-art"><span class="card-number">${i+1}</span><span class="sprite sprite-${key}" aria-hidden="true"></span><span class="card-hp">${t.hp} HP</span></div><div class="card-copy"><span class="card-name">${t.name}</span><span class="card-desc">${t.desc}</span><div class="card-bottom"><span class="card-price">${t.cost}<small> 元</small></span><span class="card-count" id="count-${key}">點擊出發</span></div></div></button>`;}).join('');$('marketHint').textContent=battle.route.origin==='長安'?'長安市集：只提供絲綢馬。':'外地市集：只提供葡萄・琵琶馬。';}
function hud(){if(!battle)return;const s=battle.state,r=battle.route;$('chapterTag').textContent=r.tag;$('chapterTitle').textContent=r.title+(s.chapter===3?` · ${s.leg==='out'?'西行':'東歸'}第 ${s.round} 趟`:'');$('originLabel').textContent=r.origin+' · 出發';$('destinationLabel').textContent=(s.chapter===0?'西域方向':r.destination)+' · 抵達';$('routeLabel').textContent=forward()?r.route.join(' → '):[...r.route].reverse().join(' ← ');$('originLabel').style.order=forward()?'0':'2';$('routeLabel').style.order='1';$('destinationLabel').style.order=forward()?'2':'0';$('dropHint').textContent=forward()?'點擊下方卡片出發 · 左 → 右':'點擊下方卡片出發 · 右 → 左';$('money').textContent=s.money.toLocaleString();$('timer').textContent=Math.max(0,Math.ceil(battle.timeLimit-battle.time));$('timerLabel').textContent=s.chapter===3?(s.leg==='out'?`距自動返程 ${Math.max(0,Math.ceil(90-battle.time))} 秒`:'東歸中 · 總剩餘'):paused?'計時已暫停':'本關剩餘';$('timerUnit').textContent='秒';$('timerBox').classList.toggle('urgent',battle.time>=battle.timeLimit-10);$('timeBar').style.width=Math.max(0,(battle.timeLimit-battle.time)/(s.chapter===3?180:battle.timeLimit)*100)+'%';$('passed').textContent=battle.deliveries.length;$('pending').textContent=battle.pending.toLocaleString();const profit=s.baseline===null?0:s.money-s.baseline;$('profit').textContent=profit.toLocaleString()+' / 10,000';$('profitBar').style.width=Math.min(100,Math.max(0,profit/100))+'%';$('pauseBtn').textContent=paused?'▶ 繼續':'Ⅱ 暫停';$('pauseBtn').disabled=s.chapter===3||battle.phase!=='running';$('pauseBtn').hidden=s.chapter===3;$('settleBtn').hidden=true;$('settleBtn').disabled=!battle.canSettle()||paused;document.querySelectorAll('.chapter-tabs span').forEach((el,i)=>el.classList.toggle('active',i===s.chapter));for(const key of keys){const b=document.querySelector(`[data-unit="${key}"]`),t=E.TYPES[key];b.hidden=!E.available(s,key);b.disabled=battle.phase!=='running'||paused||s.money<t.cost||(battle.cooldown[key]||0)>battle.time;b.classList.toggle('selected',selected===key);$('count-'+key).textContent=s.money<t.cost?'經費不足':(battle.cooldown[key]||0)>battle.time?'出發中…':`場上 ${battle.units.filter(a=>a.key===key&&a.alive&&!a.arrived).length}`;}}
function deploy(key){syncFourth();if(paused||$('dialog').open)return false;const result=battle.spawn(key);if(result.ok){say(`${E.TYPES[key].name}出發！花費 ${E.TYPES[key].cost} 元，從${forward()?'左':'右'}側出發點前進。`);}else say(result.reason);hud();return result.ok;}
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-unit]');if(b&&!b.disabled)deploy(b.dataset.unit);});
C.addEventListener('click',e=>{if(paused||$('dialog').open)return;const r=C.getBoundingClientRect(),screen=(e.clientX-r.left)/r.width*1000,x=forward()?1000-screen:screen;const a=battle.units.filter(a=>a.alive&&!a.arrived).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x))[0];if(a&&Math.abs(a.x-x)<50){selectedUnit=a.id;if(E.TYPES[a.key].animal==='camel')battle.toggle(a.id);}});
document.addEventListener('keydown',e=>{if($('dialog').open||e.repeat||/INPUT|SELECT|BUTTON/.test(e.target.tagName))return;if(/^[1-5]$/.test(e.key)){e.preventDefault();deploy(keys[+e.key-1]);}});
function forward(){return battle.route.origin==='長安'||battle.state.chapter===1;}
function screenX(x){return (forward()?1000-x:x)/1000*W;}
$('pauseBtn').onclick=()=>{if(battle.state.chapter!==3&&battle.phase==='running'){paused=!paused;hud();}};
function retry(){if(battle.state.chapter===3){state={...battle.state};restartFourth();return;}state={...battle.startState};startRound();}
$('retryBtn').onclick=()=>modal('重新挑戰','重試這一趟？','<p>恢復本趟開始前的經費，取消本趟購買與待結算收入，重新計時。</p>','確認重試',retry,'繼續目前旅程',null);
$('resetBtn').onclick=()=>modal('新的旅程','從 5,000 元重新出發？','<p>清除目前進度，回到第一關。</p>','重新開始',()=>{state=E.initial();startRound();},'保留進度',null);
$('helpBtn').onclick=()=>modal('遊戲說明','先護路，再通商',rules(),'回到戰場',null);
$('historyBtn').onclick=()=>modal('史實手記','貿易，連起文化的交流',`<p>張騫原為尋求大月氏結盟抗匈奴而出使，曾被匈奴拘留，逃出後繼續西行。後世商人沿交通網絡分段交換商品與文化。</p><div class="note">玉門關作為首次出使路標、勇氣交易、出逃時的葡萄琵琶、單一商隊往返大秦、動物裝備與價格，皆屬遊戲改編。第四關由後世商隊接棒，不是張騫活到唐代。原教材所示絲路交流，不能全部歸因於張騫本人。</div><p>依據提供的 B3L21.pdf 與教師備課資料。延伸閱讀：<a href="https://www.unesco.org/en/silk-roads/about-silk-roads" target="_blank" rel="noopener">UNESCO 絲路概說</a>、<a href="https://en.chinaculture.org/gb/en_aboutchina/2003-09/24/content_22624.htm" target="_blank" rel="noopener">張騫出使</a>。</p>`,'回到戰場',null);
function finish(){const r=battle.settle();if(!r)return;if(battle.state.ended){state={...battle.state};save();window.SilkStudent.complete(state.finalScore,state.runId);showFinal();hud();return;}hud();const s=battle.state;const plot=r.chapter===0?'離開玉門關後，匈奴攔下商隊。故事中的首領佩服你們的勇氣，留下商隊並買下通過險路的絲綢；被俘不是 game over。':r.chapter===1?'你與張騫終於抵達大月氏。對方不願結盟，但西域見聞與商貿交流仍是重要收穫。':r.chapter===2?'回到長安，西域物產與樂器讓人們認識遠方。後世商隊將接著建立更廣的交流。':`商隊抵達${r.destination}，以貿易所得準備下一趟。`;
const next=battle.advance(),win=next?.won&&s.chapter===3&&s.leg==='back';if(win&&!s.won){next.finalScore=r.balance;next.won=true;window.SilkStudent.complete(r.balance,s.runId);state=next;save();}const body=`<div class="receipt"><span>商品馬通過</span><b>${r.passed} 匹／${r.goods} 單位</b><span>本趟購買成本</span><b>−${r.spent.toLocaleString()} 元</b><span>商品出售收入</span><b>＋${r.revenue.toLocaleString()} 元</b><span>累積可用經費</span><b>${r.balance.toLocaleString()} 元</b></div><p>${win?'累積淨獲利已達 '+(s.money-s.baseline).toLocaleString()+' 元，絲路商人通關！':plot}</p><p>${r.undelivered} 匹商品馬尚未通過，不列入收入；${r.losses} 隻動物死亡。下一趟重新購買動物，剩餘經費全數保留。</p>`;
modal(s.chapter<3?`${battle.timeLimit} 秒結算`:'本趟貿易結算',win?'絲路商人，通關！':s.chapter===0?'被俘，卻沒有放棄':'商隊完成這一段旅程',body,r.balance===0?'經費用盡，重試本關':win?'繼續自由貿易':s.chapter===3?'前往 '+E.routeFor(next).origin+' 的市集 →':'進入下一關 →',()=>{if(r.balance===0)retry();else{state=next;startRound();}},'重試本關，還原經費',retry);}
function restartFourth(){state={...state,money:state.baseline,leg:'out',round:1,fourthElapsed:0,fourthSchedule:2,enemyClock:null,fourthTotals:{passed:0,goods:0,spent:0,revenue:0},ended:false,won:false,finalScore:null,runId:crypto.randomUUID()};$('scoreReceipt').hidden=true;startRound();}
function showFinal(){const totals=state.fourthTotals||{},profit=state.money-state.baseline;modal('第四關 · 總結算',state.won?'達成目標，絲路商人通關！':'3 分鐘到，貿易挑戰結束',`<div class="receipt"><span>第四關經過時間</span><b>${Math.min(180,Math.ceil(state.fourthElapsed||0))} 秒</b><span>商品馬通過總數</span><b>${totals.passed||0} 匹</b><span>商品出售總收入</span><b>${(totals.revenue||0).toLocaleString()} 元</b><span>購買總成本</span><b>${(totals.spent||0).toLocaleString()} 元</b><span>第四關淨獲利</span><b>${profit.toLocaleString()} / 10,000 元</b><span>最終金額／分數</span><b>${state.money.toLocaleString()}</b></div><p>${state.won?'已在期限內返回長安並達成獲利目標。':'180 秒結束時未達成返程獲利目標。'}時間到後停止移動、攻擊與購買；尚未抵達的商品不計收入。</p>`,'重新挑戰第四關',restartFourth,'留在結算畫面',showFinal);$('dialogHome').hidden=false;}
$('settleBtn').onclick=()=>{if(!paused)finish();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&battle?.phase==='running'&&battle.state.chapter!==3){paused=true;hud();}});
function syncFourth(){
 if(!battle||battle.state.chapter!==3||battle.phase!=='running'||fourthClock===null)return;
 const oldLeg=battle.state.leg;
 battle.step(Math.max(0,(performance.now()-fourthClock)/1000-battle.time));
 if(oldLeg!==battle.state.leg){selected=null;selectedUnit=null;$('unitInfo').hidden=true;state={...battle.state};buildCards();if($('dialog').open)$('dialog').close();modalAction=null;altAction=null;}
 if(battle.events.length)say(battle.events.splice(0).at(-1));
 if(battle.phase==='finished')finish();
}
// The world uses canvas geometry; every animal is a generated four-frame sprite.
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}function line(x,y,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}function poly(p,color){ctx.fillStyle=color;ctx.beginPath();p.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.fill();}function text(t,x,y,size=16,color='#655637'){ctx.fillStyle=color;ctx.font=`${size}px "Microsoft JhengHei",sans-serif`;ctx.textAlign='center';ctx.fillText(t,x,y);}
function gate(x,y,roman=false){ctx.save();ctx.translate(x,y);if(roman){ctx.fillStyle='#ded1ae';ctx.fillRect(-33,-57,66,57);for(let i=-27;i<30;i+=18){ctx.fillStyle='#f5ebc9';ctx.fillRect(i,-52,10,52);}poly([[-42,-56],[0,-83],[42,-56]],'#e5d8ad');}else{ctx.fillStyle='#bd9f62';ctx.fillRect(-32,-55,64,55);for(let i=-35;i<36;i+=14)ctx.fillRect(i,-66,9,16);poly([[-43,-68],[0,-83],[43,-68]],'#627666');}ctx.fillStyle='#7a7857';ctx.fillRect(-8,-29,16,29);ctx.restore();}
function drawHazard(h,y){const x=screenX(h.x),safe=battle.guard(h).length>0;if(h.type==='sand'){ellipse(x,y+7,29,9,'#ac8046');ellipse(x,y+7,19,4,'#806339');if(safe){ctx.fillStyle='#c69550';ctx.fillRect(x-30,y-5,60,7);for(let i=-25;i<30;i+=10)line(x+i,y-6,x+i,y+3,'#f4d395',2);}}else if(h.type==='wind'){ctx.globalAlpha=safe?.4:.85;for(let i=0;i<8;i++){const xx=x+Math.sin(battle.time*5+i)*4;ctx.strokeStyle='#977249';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(xx,y-7-i*7,5+i*3,2+i*.2,0,0,Math.PI*1.8);ctx.stroke();}ctx.globalAlpha=1;}else{const im=images.archer,size=W<600?90:116,age=h.shot?battle.time-h.shot.time:Infinity,frame=age<.6?Math.min(3,1+Math.floor(age/.2)):0;const faceLeft=h.shot?screenX(h.shot.x)<x:forward();ellipse(x,y+3,20,4,'#62533023');if(im.complete&&im.naturalWidth){const cell=im.width/2;ctx.save();ctx.translate(x,0);if(!faceLeft)ctx.scale(-1,1);ctx.drawImage(im,(frame%2)*cell,Math.floor(frame/2)*cell,cell,cell,-size/2,y-size+size*.08,size,size);ctx.restore();}if(h.shot&&battle.time-h.shot.time<.35){const p=Math.min(1,(battle.time-h.shot.time)/.25),end=screenX(h.shot.x),xx=x+(end-x)*p;line(xx,y-45+30*p,xx+(end>x?-12:12),y-48+30*p,'#693e28',3);text('−10',end,y-98,15,'#a0412d');}}
text(safe?'駐守中':h.type==='sand'?'流沙':h.type==='wind'?'龍捲風':'弓箭手',x,y+34,W<600?13:16,safe?'#3b755d':'#756044');}
function drawUnit(a,y){const t=E.TYPES[a.key],im=images[a.key],x=screenX(a.x),size=W<600?99:144;if(!im.complete||!im.naturalWidth)return;const stationary=a.stopped||a.waitingFor!==null,frame=battle.phase==='running'&&!paused&&!$('dialog').open&&!stationary?Math.floor(battle.time*(t.animal==='horse'?9:6)+a.id)%4:0;ellipse(x,y+4,size*.28,5,'#62533023');const cell=im.width/2;ctx.save();ctx.translate(x,0);if(forward())ctx.scale(-1,1);ctx.drawImage(im,(frame%2)*cell,Math.floor(frame/2)*cell,cell,cell,-size/2,y-size+size*.08,size,size);ctx.restore();const bar=45;ctx.fillStyle='#877854';ctx.fillRect(x-bar/2,y-size*.88,bar,5);ctx.fillStyle=a.hp/a.maxHp>.3?'#427b60':'#b55339';ctx.fillRect(x-bar/2,y-size*.88,bar*a.hp/a.maxHp,5);if(a.guardId!==null){text(Math.ceil(a.hp)+' HP',x,y-size*.88-6,13,'#345b42');}}
function drawEnemy(e,ground){
 const im=images[e.kind];if(!im.complete||!im.naturalWidth)return;
 const crow=e.kind==='crow',size=W<600?(crow?84:94):(crow?120:130),x=screenX(e.x);
 const rise=crow?1:Math.min(1,e.age/.7,(5.2-e.age)/.7);
 const y=crow?ground-175+e.y*135:ground+12;
 const frame=Math.floor(e.age*(crow?9:5))%4,cell=128;
 ctx.save();
 if(!crow){ellipse(x,ground+7,size*.43,9,'#885c3e55');ctx.beginPath();ctx.rect(x-size,ground-size*rise,2*size,size*rise+15);ctx.clip();}
 if(crow&&e.carried){const cargo=images[e.carried];if(cargo.complete&&cargo.naturalWidth){const c=cargo.width/2;ctx.drawImage(cargo,0,0,c,c,x-size*.33,y-10,size*.66,size*.66);}}
 ctx.drawImage(im,(frame%2)*cell,Math.floor(frame/2)*cell,cell,cell,x-size/2,y-size+(crow?0:(1-rise)*size),size,size);
 ctx.restore();
 text(crow?(e.carried?'驚盗鴉 · 抓走馬與貨物！':'驚盗鴉'):(e.hit?'沙蟲 · 吞噬！':'沙蟲 · 只攻擊馬'),x,crow?y-size-6:ground-size-9,W<600?12:15,'#8b3d30');
}
function draw(){ctx.clearRect(0,0,W,H);const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#f5e8c4');sky.addColorStop(1,'#e8c887');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ellipse(W*.73,H*.19,32,32,'#e6b25a');for(let layer=0;layer<3;layer++){const p=[[-50,H]];for(let i=-1;i<12;i++)p.push([i*W/8,H*(.39+layer*.09)+Math.sin(i*1.7+layer)*H*.085]);p.push([W+50,H]);poly(p,['#d0c7a4','#d3b788','#ddba7c'][layer]);}const ground=H*.78;ctx.fillStyle='#efd39e';ctx.fillRect(0,ground-12,W,H-ground+12);line(0,ground+18,W,ground+18,'#bd985b',1);for(let i=0;i<18;i++)line(i*W/17,H*.94-(i%3)*6,i*W/17+8,H*.94-(i%3)*6-2,'#baa16c');SilkCities.draw(ctx,battle.route.route,W,ground,forward());battle.hazards.forEach(h=>drawHazard(h,ground));battle.units.filter(a=>a.alive&&!a.arrived).sort((a,b)=>a.spawned-b.spawned).forEach(a=>drawUnit(a,ground+(a.id%3)*5));battle.enemies.forEach(e=>drawEnemy(e,ground));if(battle.phase==='ready'){text('先派守護駱駝，再讓商品馬通過。',W/2,H*.18,W<600?18:24,'#907744');}if(paused){ctx.fillStyle='#344d394d';ctx.fillRect(0,0,W,H);text('旅程暫停',W/2,H/2,30,'#fff9e8');}const unit=battle.units.find(a=>a.id===selectedUnit);if(unit&&unit.alive&&!unit.arrived){$('unitInfo').hidden=false;$('unitInfo').textContent=`${E.TYPES[unit.key].name} · ${Math.ceil(unit.hp)} / ${unit.maxHp} HP${unit.guardId!==null?' · 駐守中':unit.manualStop?' · 已停下':unit.waitingFor!==null?' · 等待前方通道':' · 前進中'}`;}else $('unitInfo').hidden=true;}
function resize(){const r=C.getBoundingClientRect();W=r.width;H=r.height;const dpr=Math.min(2,devicePixelRatio||1);C.width=Math.round(W*dpr);C.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}window.addEventListener('resize',resize);
function frame(ts){const dt=Math.min((ts-last)/1000,.08);last=ts;if(battle?.state.chapter===3)syncFourth();else if(battle&&!paused&&!$('dialog').open){battle.step(dt);if(battle.events.length)say(battle.events.splice(0).at(-1));if(battle.phase==='finished')finish();}hud();draw();requestAnimationFrame(frame);}
window.SilkStudent.ready.then(()=>{load();if(!state.runId)state.runId=crypto.randomUUID();startRound();resize();requestAnimationFrame(frame);});
if(new URLSearchParams(location.search).has('test'))window.silkTest={get:()=>({battle,state,paused,selected,imagesReady}),step:dt=>{battle.step(dt);if(battle.phase==='finished')finish();hud();draw();},spawn:deploy,setState:s=>{state={...E.initial(),...s};startRound();},finish,draw,screenX,forward};
})();
