/* Bundle the pinned Three.js distribution for classic-script/file:// use.
 * This deliberately supports only the named imports/exports in the checked-in
 * r180 files. Unsupported module syntax fails rather than silently changing it.
 * No runtime eval or external dependency is needed by the generated bundle.
 */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const properties = list => list.split(',').map(entry => {
  const parts = entry.trim().split(/\s+as\s+/);
  if (!parts.every(p => /^[A-Za-z_$][\w$]*$/.test(p))) throw new Error('Unsupported export: ' + entry);
  return parts.length === 2 ? `${parts[1]}: ${parts[0]}` : parts[0];
}).join(', ');
function wrap(source, dependency) {
  const exports = [];
  source = source.replace(/^import \{([^}]+)\} from '\.\/three\.core\.js';\s*$/gm,
    (_, names) => `const { ${properties(names)} } = core;`);
  source = source.replace(/^export \{([^}]+)\} from '\.\/three\.core\.js';\s*$/gm, (_, names) => {
    exports.push(`...(() => { const { ${properties(names)} } = core; return { ${properties(names)} }; })()`);
    return '';
  });
  source = source.replace(/^export \{([^}]+)\};\s*$/gm, (_, names) => { exports.push(properties(names)); return ''; });
  if (/^\s*(import|export)\s/m.test(source) || !exports.length) throw new Error('Unexpected Three.js module shape');
  if (!dependency && /\bfrom '\.\//.test(source)) throw new Error('Unexpected core dependency');
  return `(() => {\n${source}\nreturn { ${exports.join(', ')} };\n})()`;
}
const core = wrap(read('vendor/three.core.js'), false);
const three = wrap(read('vendor/three.module.js'), true);
let scene = read('maze-scene.js');
if (!scene.includes("import * as THREE from './vendor/three.module.js';")) throw new Error('Unexpected scene import');
scene = scene.replace("import * as THREE from './vendor/three.module.js';", '').replace('export function createMazeScene', 'function createMazeScene');
if (/^\s*(import|export)\s/m.test(scene)) throw new Error('Unexpected scene module shape');
const bundle = `/* Generated by node tools/build-maze.cjs. Do not edit directly.
 * Includes Three.js r180, MIT license: vendor/THREE-LICENSE.txt.
 */\nwindow.MazeScene = (() => {\n'use strict';\nconst core = ${core};\nconst THREE = ${three};\n${scene}\nreturn { createMazeScene };\n})();\n`;
fs.writeFileSync(path.join(root, 'maze-scene.bundle.js'), bundle);
console.log('Built maze-scene.bundle.js (' + Buffer.byteLength(bundle) + ' bytes)');
