// Vendor the pinned browser build for Apps Script's V8 runtime (no Node APIs).
const fs = require('node:fs');
const path = require('node:path');
const base = path.dirname(require.resolve('node-forge/package.json'));
const target = path.resolve(__dirname, '../gas');
const source = fs.readFileSync(path.join(base, 'dist/forge.min.js'), 'utf8');
fs.writeFileSync(path.join(target, 'Forge.js'),
  '// Generated by npm run build:auth. node-forge 1.4.0; see FORGE-LICENSE.txt.\n' +
  'function createForgeVerifier() {\nvar window = {}, self = window;\n' + source +
  '\nreturn window.forge;\n}\n');
fs.copyFileSync(path.join(base, 'LICENSE'), path.join(target, 'FORGE-LICENSE.txt'));
